- src/db/schemas/cart-schema.js
- src/routers/admin-router.js
- src/routers/auth-router.js
- src/routers/image-router.js
- src/routers/order-router.js
- src/routers/user-router.js
- src/services/product-service.js
> [221116] [BE] 타입변경 롤백

- src/views/product_detail/product_detail.js
장바구니 항목이 존재할 때, 주문하기 클릭시 장바구니 항목은 그대로 두며, 해당 항목만 주문하도록 합니다.
- 현재 구현된 사항은 주문하기 클릭시 리다이렉션 기능(회원 / 비회원에 따라 order페이지로 이동)만 존재합니다.
- 중첩 if문의 리팩토링 작업을 시도하였으나, 쉽지 않았기에 추후 다른 분께 도움 요청 하겠습니다.
> [221117] [FE] 주문하기 클릭 시 장바구니 비우기 롤백

- src/views/admin/category_admin.js
- src/views/admin/order_admin.js
- src/views/admin/product_admin.js
- src/views/category_page/category_page.js
- src/views/constants/Keys.js
- src/views/event_page/event_page.js
- src/views/home/home.html
- src/views/home/home.js
- src/views/product_detail/product_detail.css
- src/views/product_detail/product_detail.js
- src/views/template/header/header.js
- src/views/utils/useful_functions.js
- 수량 조절 옵션을 추가하였습니다.
- 바로 주문하기 버튼 클릭 시 기존 localStorage 키 products에 저장하는 것이 아닌, 다른 키에 값을 저장을 합니다.
- 프리티어 single quote -> double quotes 적용
- API 요청 주소를 constants/ApiUrl.js 에서 가져왔습니다.
- HTML내 자바스크립트의 타입을 module로 설정할 시 DOM요소를 제대로 못찾는 버그를 고쳤습니다.
> [221118] [FE] 상품 상세 페이지 내 수량 조절 옵션 추가

- src/db/schemas/user-schema.js
- src/views/join/join-success.css
- src/views/join/join-success.html
- src/views/join/join-success.js
- src/views/utils/findAddress.js
1. 다음 API를 이용하여 주소를 검색하는 기능 추가.
- findAddress.js 파일을 utils폴더에 추가함. (비동기처리)
2. user-schema에 추가된 postalCode 프로퍼티 추가.
-  address내의 객체로 추가정보를 받기 때문에 user-schema만 수정하였음.
> [221118] [FE] [BE] 다음 주소 검색 기능 추가 및 적용

- src/utils/sorting-cart.js
> [221119] [BE] cart 응답 타입 변경

- src/views/cart/cart.js
- src/views/constants/Keys.js
- src/views/order_pay/order_pay.js
- src/views/product_detail/product_detail.js
- src/views/template/header/header.js
1. CART_KEY, ORDER_KEY로 localStorage 키값 변경
2. 장바구니에서 주문버튼 눌렀을 때 체크된 상품들만 ORDER_KEY로 localStorage에 저장
3. 주문페이지에서 ORDER_KEY로 주문할 상품들 불러오기
> [221119] [FE] 장바구니에서 체크된 상품만 주문페이지로 넘어가도록 수정

- src/views/product_detail/product_detail.js
- src/views/utils/cart.js
> [221119] [FE] 덮어씌워진 상품상세 페이지 코드 복구, 기능 추가

- src/db/models/product-model.js
- src/db/schemas/product-schema.js
- src/routers/product-router.js
- src/services/product-service.js
- src/utils/index.js
- src/utils/pagination.js
필터링 조회 기능 추가
pagination 개선 ( db리소스 )
> [221120] [BE] 필터링 조회 기능 추가

- src/routers/product-router.js
- src/services/product-service.js
- src/utils/index.js
- src/utils/make-filterObj.js
> [221120] [BE] 필터링 조회 기능 개선

- src/views/admin/product_admin.js
- src/views/category_page/category_page.js
- src/views/product_detail/product_detail.css
- src/views/product_detail/product_detail.js
- 상품 상세보기 버튼을 누르고 또 다른 상세 버튼을 눌렀을 때, 여전히 상세라고 뜨는 버그를 고쳤습니다.
- 카테고리 페이지: 새로운 상품 데이터 요청 방식을 적용하였으며, 반복문을 즉시 실행 함수로 감싸, 보기 쉽게 하였습니다.
> [221120] [FE] 관리자 페이지 - 상품 관리 버그 수정 및 카테고리 페이지 리팩토링

- src/db/models/category-model.js
- src/db/models/product-model.js
- src/routers/category-router.js
- src/services/category-service.js
- src/services/product-service.js
1. 카테고리 기능 개선 : 카테고리 삭제시 → 카테고리에 속한 상품들 카테고리 ”없음” 으로 변경 → "없음" 카테고리에 상품들 추가
2. 상품 수정기능중 카테고리와 연동 안되던 몇가지 수정
> [221122] [BE] 카테고리 기능 개선 + 상품 수정기능 fix

- src/utils/make-filterObj.js
> [221123] [BE] 필터검색기능 수정

- src/services/product-service.js
> [221123] [BE] 상품 삭제 fix

- src/views/order_list/order_list.css
- src/views/order_list/order_list.html
- src/views/order_list/order_list.js
- 상세정보보기 버튼을 추가하여 눌렀을 때 주문정보, 결제내역이 보이도록 수정하였습니다.
- 기존 배송정보 컨테이너를 주문정보, 결제내역으로 분리하였습니다
- 다음 api주소 찾기를 추가하였습니다
> [221123] [FE] 회원 주문내역 결제내역 컨테이너 추가

- src/views/user_information/user_information.html
- src/views/user_information/user_information.js
- 마이페이지에 들어가면 보이던 회원 탈퇴 버튼을 사용자 상세 페이지로 이동시켰습니다.
> [221124] [FE] 사용자정보페이지에 회원탈퇴 기능 추가

- src/services/order-service.js
> [221124] [BE] 주문취소 fix

- src/routers/product-router.js
- src/services/product-service.js
- src/utils/make-filterObj.js
> [221124] [BE] 키워드 검색기능 추가

- src/views/template/main_style.css
> [221125] 메인 컬러, 버튼 파일 추가

- src/views/template/main_style.css
> [221125] [FE] 폰트 종류, 공통 폰트 사이즈와 버튼 추가

- src/services/user-service.js
> [221128] [BE] update token expired time

- src/views/user_information/user_information.css
- src/views/user_information/user_information.html
- 전체적인 사이즈를 줄였습니다
- input창 디자인을 바꿨습니다
> [221129] [FE] 사용자 정보페이지 css작업

- src/views/order_list/order_list.css
- src/views/order_list/order_list.js
- 장바구니 페이지 크기에 맞게 주문내역 페이지를 수정했습니다
- input창 수정했습니다
- max-width 추가했습니다
- 전체적인 글자크기 수정했습니다
- 상품 이미지 불러오는 코드 추가했습니다
> [221129] [FE] 회원 주문내역 페이지 css작업

- src/views/myPage/myPage.css
- 회원 주문내역 페이지와 동일하게 css작업했습니다
- 상품 이미지 불러오는 기능 추가했습니다
- 전체적인 크기 수정했습니다
> [221129] [FE] 마이페이지(+비회원 주문내역 페이지) css 작업

- src/views/category_page/category_page.css
- src/views/event_page/event_page.css
- src/views/event_page/event_page.js
- 기획전 페이지 내 상품 UI가 하나씩 밀리는 현상을 고쳤습니다.
- 카테고리 페이지와 UI 스타일을 통일하였습니다.
> [221129] [FE] 기획전 페이지 버그 해결과 UI 통일

- src/services/comment-service.js
> [221129] [BE] comment 삭제 버그 fix

- src/views/category_page/category_page.js
- src/views/event_page/event_page.css
- src/views/home/home.css
- src/views/template/header/header.css
- src/views/template/header/header.js
- 페이지 클릭 시 쿼리스트링을 통해 리다이렉트 합니다.
- 이제 refineData 함수에서 모든 상품 데이터가 모인 배열을 페이지별로 자릅니다.
- 함수 순서 및 동일한 변수 선언을 전역으로 빼주는 등의 리팩토링을 진행하였습니다.
> [221130] [FE] 페이지네이션 페이지화 구현

- src/views/home/home.css
- src/views/product_detail/product_detail.css
- src/views/product_detail/review.css
- src/views/template/main_style.css
1. 반응형으로 제작 (모바일 고려 414px, 웹 768px, ... 이외 세세한 수정이 필요할 시 더 넣음)
2. main_style.css에서 사용되는 button 56 반응형으로 추가해둠. (확인 후 디테일하게 수정 필요)
이전 PR에서 누락되었던 코드 추가
> [221130] [FE] 77번 PR에서 누락되었던 내용 추가

- src/views/adult_certification/adult_certification.css
- src/views/adult_certification/adult_certification.html
- src/views/join/join-success.css
- src/views/join/join.css
- src/views/join/join.html
- src/views/login/login.css
- src/views/myPage/myPage.css
- src/views/myPage/myPage.js
- src/views/order_list/order_list.css
- src/views/order_list/order_list.js
- input박스에 파란테두리 나타나는 부분 없앴습니다
- 기존 흰색버튼(검정테두리) -> 새로운 흰색버튼으로 수정했습니다
- 피드백 받은 문구 수정, 삭제 작업 했습니다
- 이메일 중복 버튼 간격 만들었습니다
- 주문상세보기 버튼 마우스 올렸을 때 색 변하도록 수정했습니다
- 비회원 주문 시 뜨는 성인인증 창 css작업 완료했습니다
> [221130] [FE] 마이페이지, 가입페이지, 성인인증페이지, ... 피드백 css수정

- src/routers/views-router.js
- src/views/filter/filter.css
- src/views/filter/filter.html
- src/views/filter/filter.js
- src/views/home/home.html
- src/views/home/home.js
홈 화면에서 알콜타입을 클릭하면 search filter API를 이용하여 주종 별 상품을 로드한 페이지로 directing
> [221130] [FE] 알콜타입 아이콘 클릭 시 필터링 후 해당 상품 나열

- src/views/myPage/myPage.js
- src/views/order_list/order_list.css
- src/views/order_list/order_list.js
- 주문상세정보 클릭 시 열림, 닫힘 기능 수정
- 입력창 alert메세지 수정
- 주문상세 정보 최신 순으로 정렬 기능 수정
> [221201] [FE] 주문내역 페이지 버그 수정

- src/views/home/home.css
- src/views/home/home.html
- src/views/home/home.js
- src/views/product_detail/product_detail.css
1. 홈과 제품상세 페이지에서 세세한 피드백들 수정
2. 반응형 적용 시 자연스럽게 움직이도록 수정
3. 폰트 사이즈 var 형식으로 수정 (home.css에만 적용하였음. product-detail에는 건드리기에 이전에 했던 것들이 깨져서 편의 상 적용하지 않음.)
4. 제품 상세 페이지에서 768px 미만일 시 모바일 환경에 적합하도록 디자인 전체적으로 수정함.
> [221201] [FE] 홈, 제품 상세 css 수정

- src/views/home/home.css
- src/views/template/footer/footer.css
- src/views/template/footer/footer.js
- src/views/template/header/header.css
- src/views/template/header/header.js
- src/views/template/main_style.css
- 이제 모바일 환경의 헤더에서 장바구니가 햄버거메뉴 옆에 위치합니다.
- 모바일 환경에서의 푸터 CSS를 적용하였습니다.
- main css에서 body container의 margin-top 값을 삭제하였습니다.
> [221201] [FE] 홈, 푸터 모바일 환경 CSS 수정 및 헤더 모바일 환경 장바구니 추가

- src/views/home/home.css
- src/views/home/home.html
- src/views/product_detail/product_detail.css
- src/views/product_detail/product_detail.js
- src/views/product_detail/review.css
1. 홈 화면 피드백 내용 수정(알콜타입 아이콘 일자 배치가 가장 나아보여서 반응형 구간을 세분화해서 일자로 유지되도록 함)
2. 제품 상세 페이지 버튼 재배치, 글자크기 및 위치 수정
3. 각종 배치 관련 패딩, 마진, 디스플레이 등등 수정
> [221201] [FE] 홈, 제품 상세 / 피드백 바탕으로 수정

- src/views/home/home.css
슬라이더 내 상품 이름, 가격에 폰트 크기를 반응형으로 적용 / color 수정
> [221201] [FE] 홈화면 슬라이더(화면 축소 시 폰트 반응형으로 적용)

- src/db/README.md
ERD구성도를 README에 첨부하여 db디렉토리에 참조하여 이해도를 높히기 위해 추가함.
> [221202] [BE] README 추가(db)

- src/views/my_order_list/my_order_list.js
- src/views/my_page/my_page.css
- 마이페이지 첫 화면 전체적인 크기 사이즈 줄임
- 비빌번호 입력 페이지 모바일 화면에 맞게 수정
> [221202] [FE] 마이페이지 css수정

- src/views/join/join.css
- src/views/my_order_list/my_order_list.css
- src/views/my_page/my_page.css
> [221202] [FE] 주문내역 css 수정

- src/views/my_order_list/my_order_list.js
> [221208] [FE] 상품금액  합계 오류 로직 수정
